---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "iag.labels" . | nindent 4 }}
    app.kubernetes.io/component: "service"
  annotations:
    kubernetes.io/description: "Itential Automation Gateway service."
    {{- include "iag.annotations" . | nindent 4 }}
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.applicationPort }}
      protocol: TCP
  selector:
    {{- include "iag.selectorLabels" . | nindent 4 }}
